# gradle.properties

# Projekt pouziva AndroidX knihovny (Room, WorkManager, AppCompat, atd.) - bez tohohle build spadne.
android.useAndroidX=true
android.enableJetifier=false

# Standardni doporucena nastaveni pro rychlejsi build
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
kotlin.code.style=official
